#!/usr/bin/env zsh

set -e

port=2375

cmd=

if [ $# -gt 0 ]; then
    cmd=$1; shift
fi

case "$cmd" in
    create)
        multipass launch -n dockerhost -c 2 -d 10G -m 2G --cloud-init =(cat << EOF
---
package_update: true
package_upgrade: true
write_files:
- path: /etc/systemd/system/docker.service.d/options.conf
  owner: root:root
  permissions: '0644'
  content: |
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:$port --containerd=/run/containerd/containerd.sock
runcmd:
  - curl -fsSL https://get.docker.com | sudo bash
  - sudo systemctl enable docker
  - sudo groupadd docker
  - sudo usermod -aG docker ubuntu
EOF
) "$@"
        multipass info dockerhost
        echo
        echo "Run the following to setup the DOCKER_HOST environment variable:"
        echo "  eval \$(dockerhost env)"
        echo
        echo "Or set the DOCKER_HOST environment variable:"
        ip=$(multipass info dockerhost --format json | jq -r '.info.dockerhost.ipv4[0]')
        echo "  export DOCKER_HOST=\"tcp://$ip:$port\""
        ;;
    info)
        multipass info dockerhost
        ;;
    ip)
        ip=$(multipass info dockerhost --format json | jq -r '.info.dockerhost.ipv4[0]')
        echo "$ip"
        ;;
    env)
        ip=$(multipass info dockerhost --format json | jq -r '.info.dockerhost.ipv4[0]')
        echo "export DOCKER_HOST=\"tcp://$ip:$port\""
        ;;
    exec)
        multipass exec dockerhost -- "$@"
        ;;
    start)
        multipass start dockerhost
        ;;
    stop)
        multipass stop dockerhost
        ;;
    mount)
        multipass mount $1 dockerhost:$2
        ;;
    umount)
        multipass umount dockerhost:$1
        ;;
    delete)
        multipass delete dockerhost
        multipass purge
        ;;
    *)
        echo "Usage: dockerhost <command>"
        echo
        echo "Example:"
        echo "  dockerhost create -c 2 -d 10G -m 2G"
        echo "  dockerhost mount \$HOME \$HOME"
        echo "  eval \$(dockerhost env)"
        echo "  docker build ..."
        echo
        echo "Commands:"
        echo "  create  Create and start a vm hosting the docker daemon."
        echo "            -c Number of CPUs to allocate. Default: 2."
        echo "            -d Disk space to allocate. Default: 10G."
        echo "            -m Memory to allocate. Default: 2G."
        echo "  start   Start the vm."
        echo "  stop    Stop the vm."
        echo "  delete  Delete the vm."
        echo "  info    Display the IP, disk space, and other info about the vm."
        echo "  ip      Display the IP of the vm."
        echo "  env     Output the DOCKER_HOST environment variable."
        echo "  exec    Execute a command in the vm."
        echo "  mount   Mount a folder into the vm."
        echo "            <source> The folder on the host."
        echo "            <target> The folder on the dockerhost. (Optional)"
        echo "  umount  Unmount a folder that was mounted into the vm."
        echo "            <target> The folder on the dockerhost. (Optional)"
        exit 1
        ;;
esac
